#!/bin/bash
###########################
DEVICE=6
WORK_DIR='/home/hyunsoocha/GitHub/perse_dev'
DATASET_NAME=han
DRIVING_VIDEO_DIR=$WORK_DIR/data/datasets/$DATASET_NAME/driving_videos/portrait_image_imavatar_mvi_1810_1812_limit.mp4         # generated by LivePortrait.
TARGET_DIR=$WORK_DIR/data/datasets/$DATASET_NAME/driving_videos                 # save directory
EXT='jpg'
IMG_DIR_NAME='image'
###########################
SUBMODULE_DIR=$WORK_DIR/code/submodules
DWPOSE_DIR=$SUBMODULE_DIR/DWPose
EMOCA_DIR=$SUBMODULE_DIR/emoca
SAPIENS_DIR=$SUBMODULE_DIR/sapiens
###########################

echo "[INFO] mp4 to video"
mkdir -p $TARGET_DIR
mkdir -p $TARGET_DIR/$IMG_DIR_NAME

cd $TARGET_DIR
ffmpeg -i $DRIVING_VIDEO_DIR -qscale:v 1 -vf "fps=30" $TARGET_DIR/$IMG_DIR_NAME/%4d.$EXT

echo "[INFO] DWPose"
cd $DWPOSE_DIR
./run_dwpose.sh $DEVICE $TARGET_DIR $DWPOSE_DIR $IMG_DIR_NAME

echo "[INFO] EMOCA"
cd $EMOCA_DIR
./run_emoca.sh $DEVICE $TARGET_DIR $EMOCA_DIR $IMG_DIR_NAME